version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=apiary
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_INIT_TOKEN}
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    build: ./telegraf
    environment:
      - INFLUX_INIT_TOKEN=${INFLUX_INIT_TOKEN}
    depends_on:
      - influxdb

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD-SHELL", "timeout 3 bash -c '</dev/tcp/localhost/1883' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  grafana:
    build: ./grafana
    environment:
      - INFLUX_INIT_TOKEN=${INFLUX_INIT_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  ota:
    build: ./ota
    ports:
      - "8080:8080"

  api:
    build: ./api
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - ota

volumes:
  influxdb_data: