version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=apiary
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_INIT_TOKEN}
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    build: ./telegraf
    environment:
      - INFLUX_INIT_TOKEN=${INFLUX_INIT_TOKEN}
    depends_on:
      - influxdb

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD-SHELL", "timeout 3 bash -c '</dev/tcp/localhost/1883' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  grafana:
    build: ./grafana
    environment:
      - INFLUX_INIT_TOKEN=${INFLUX_INIT_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  beewax-api:
    build: ./api
    ports:
      - "5000:5000"

  # Servidor OTA (servidor de archivos estáticos + proxy a API)
  # Comentado porque en Easypanel se configura como beewax-nginx
  # ota-server:
  #   image: nginx:alpine
  #   container_name: ota-server
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./ota:/srv/ota:ro
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/sites:/etc/nginx/sites:ro
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/fw/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   deploy:
  #     resources:
  #       limits: { memory: 64M }
  #       reservations: { memory: 32M }
  #   depends_on:
  #     - beewax-api

volumes:
  influxdb_data: